info:
  contact: {}
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: Test endpoint
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Ping
      tags:
      - test
swagger: "2.0"
